#pragma once

enum ObjectID
{
	FullBedrock=-3,
	FullSpace=-2,
	Space=0,
	Zonk=1,
	BaseX=2,
	HardwareBlueLed=3,
	HardwareBrick1=4,
	HardwareBlueResistance=5,
	HardwareGreenLed=6,
	HardwareRedLed=7,
	HardwareResource=8,
	HardwareResistance=9,
	HardwareStripLine=10,
	HardwareYellowResistance=11,
	HardwareRedCapacitor=12,
	Bug=13,
	Infotron=14,
	Exit=15,
	CrossPort=16,
	DualPortHorizontal=17,
	DualPortVertical=18,
	OneWayPortDown=19,
	OneWayPortLeft=20,
	OneWayPortRight=21,
	OneWayPortUp=22,
	RAMChipsMini=23,
	RAMChipsLeft=24,
	RAMChipsRight=25,
	Electrons=26,
	SnikSnakMove=27,
	Terminal=28,
	Utility1=29,
	Utility2=30,
	Utility3=31,
	ExplosionEffect=32,
	Explosion =33,
	ExplosionExpansive=34,
	RAMChipsTop=35,
	RAMChipsBottom=36,
	HardwareSwitch=37,
	OneWayPortDownGrav = 38,
	OneWayPortLeftGrav = 39,
	OneWayPortRightGrav = 40,
	OneWayPortUpGrav = 41,
	Player=42,
	PlayerPlus=43,
};